# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 4399
  servlet:
    # 应用的访问路径
    context-path: /ruoyi-fast

# Spring配置
spring:
  profiles:
    active: druid


# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/*.xml





